"""add gend

Revision ID: 423183c089fe
Revises: e0893f34176c
Create Date: 2022-02-03 21:27:36.529910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423183c089fe'
down_revision = 'e0893f34176c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
