"""upgrade

Revision ID: e0893f34176c
Revises: 26cba93f31c4
Create Date: 2022-02-03 21:21:27.869031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0893f34176c'
down_revision = '26cba93f31c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('phone', sa.VARCHAR(), server_default=sa.text("'00000'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
